// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsStringsOps "github.com/acme-kuetix/acme-std-strings/modules/strings/ops/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["strings/ops"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"strings/ops"+"/"+"ops", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "ops", Impl: transitionsStringsOps.NewOpsTransitions() }})
	}
}
